languageCode = "en"
DefaultContentLanguage = "en"
title = ""
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

paginate = 10

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"

[params]
title = "Richard \"Rick\" Roché"
author = "Rick Roché"
description = "Software Engineer, Solutions Architect, Hiking Enthusiast"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
# customCss = []
customCss = ["css/custom.css"]
# example ["js/custom.js"]
customJs = []
mainSections = ["posts"]
# mainSections = []
images = ["images/site-feature-image.png"]
# doNotLoadAnimations = false
doNotLoadAnimations = true
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
displayMode = "dark"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/richardjroche/"

[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/rick-roche"

[[params.socialIcons]]
icon = "fab fa-goodreads"
title = "goodreads"
url = "https://www.goodreads.com/rick_roche"

# [[params.socialIcons]]
# icon = "fab fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

# [[params.socialIcons]]
# icon = "fas fa-envelope"
# title = "e-mail"
# url = "mailto:mail@alexbilz.com"

## Menu items
[menu]
  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
  name = "Tags"
  weight = 500
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "Archives"
  weight = 600
  identifier = "archives"
  url = "/archives/"
