[build]
base = "site/"
publish = "public"
command = "git submodule update --init --recursive --force --remote && cd themes/LoveIt && git checkout v0.2.11 && cd - && hugo --gc --minify -b https://www.rickroche.com/"

[context.production.environment]
HUGO_VERSION = "0.114.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "git submodule update --init --recursive --force --remote && cd themes/LoveIt && git checkout v0.2.11 && cd - && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.114.1"

[context.branch-deploy]
command = "git submodule update --init --recursive --force --remote && cd themes/LoveIt && git checkout v0.2.11 && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.114.1"

[dev]
base = "site/"
framework = "#custom"
command = "hugo -s site/ server --buildDrafts --buildFuture -b http://localhost:8888  -w"
port = 8888
targetPort = 1313
